name: VytherisUtils
main: dev.glhrrm.vytherisfly.Main
version: 1.0
commands:
  fly:
    aliases: [voar]
  gm0:
    aliases: [gmc]
  gm1:
    aliases: [gmc]
  gm2:
    aliases: [gma]
  gm3:
    aliases: [gmsp]
  ping:
    aliases: [latencia]